version: 2
updates:
  - package-ecosystem: nuget
    directory: /apps/desktop
    schedule: { interval: weekly }
  - package-ecosystem: gradle
    directory: /apps/android
    schedule: { interval: monthly }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: monthly }
