from __future__ import annotations

import hashlib
from typing import Any, Callable

from .client import CoreHostClient
from .models import ServerRecord, SourceDefinition, utc_now
from .sources import normalize_sources
from .storage import JsonStore
from .subscription import fetch_subscription

ProgressCallback = Callable[[int, int], None]


class AppService:
    """Product/business layer for Version 3.

    Subscription authority stays in dicodePing.  Raw subscription payloads are
    handed to the desktop runtime only for protocol parsing/profile management.
    """

    def __init__(self, store: JsonStore, runtime: CoreHostClient) -> None:
        self.store = store
        self.runtime = runtime

    def sources(self, language: str = "fa") -> list[SourceDefinition]:
        return normalize_sources(self.store.load_settings(), language=language)

    @staticmethod
    def _record_id(source_id: str, profile: dict[str, Any]) -> str:
        # Runtime profile IDs may be regenerated when a subscription refreshes.
        # Product identity must instead follow the normalized proxy definition so
        # favorites, selection and historical latency survive a refresh.
        identity = str(profile.get("share_uri") or "").strip()
        if not identity:
            identity = "\0".join(str(profile.get(key) or "") for key in (
                "type", "host", "port", "network", "security", "name",
            ))
        return hashlib.sha256(f"{source_id}\0{identity}".encode()).hexdigest()[:24]

    def refresh(self, progress: ProgressCallback | None = None, language: str = "fa") -> list[ServerRecord]:
        old = {server.id: server for server in self.store.load_servers()}
        result: list[ServerRecord] = []
        enabled = [s for s in self.sources(language) if s.enabled]
        total = max(1, len(enabled))
        for index, source in enumerate(enabled):
            payload = fetch_subscription(source)
            profiles = self.runtime.sync_source(source.id, payload.content)
            for profile in profiles:
                profile_id = str(profile.get("id") or "")
                if not profile_id:
                    continue
                record_id = self._record_id(source.id, profile)
                previous = old.get(record_id)
                record = ServerRecord(
                    id=record_id,
                    name=str(profile.get("name") or "Server"),
                    protocol=str(profile.get("type") or "UNKNOWN").upper(),
                    host=str(profile.get("host") or ""),
                    port=int(profile.get("port") or 0),
                    config_blob=str(profile.get("share_uri") or ""),
                    source_id=source.id,
                    source_name=source.name,
                    source_order=source.order,
                    core_profile_id=profile_id,
                    network=str(profile.get("network") or ""),
                    transport_security=str(profile.get("security") or ""),
                    favorite=bool(previous.favorite) if previous else False,
                    last_connected=previous.last_connected if previous else "",
                    ping_ms=previous.ping_ms if previous else None,
                    status=previous.status if previous else "unknown",
                )
                result.append(record)
            if progress:
                progress(index + 1, total)
        # Local Scanner profiles are generated by the V3 runtime and have no
        # remote subscription URL; retain them across authoritative refreshes.
        scanner_rows = [row for row in old.values() if row.source_id.startswith("scanner-")]
        known = {row.id for row in result}
        result.extend(row for row in scanner_rows if row.id not in known)
        result.sort(key=self._sort_key)
        self.store.save_servers(result)
        return result

    @staticmethod
    def _sort_key(server: ServerRecord) -> tuple[Any, ...]:
        return (
            0 if server.favorite else 1,
            server.ping_ms if server.ping_ms is not None else 1_000_000,
            server.source_order,
            server.name.casefold(),
        )

    def servers(self) -> list[ServerRecord]:
        rows = self.store.load_servers()
        rows.sort(key=self._sort_key)
        return rows

    def select_best(self) -> ServerRecord | None:
        rows = self.servers()
        online = [r for r in rows if r.ping_ms is not None]
        return (online or rows)[0] if rows else None

    def test_latency(self, records: list[ServerRecord] | None = None) -> list[ServerRecord]:
        all_rows = self.store.load_servers()
        target_ids = {r.id for r in records} if records is not None else {r.id for r in all_rows}
        profiles = [r.core_profile_id for r in all_rows if r.id in target_ids and r.core_profile_id]
        values = self.runtime.latency(profiles)
        checked = utc_now()
        for row in all_rows:
            if row.id not in target_ids or not row.core_profile_id:
                continue
            row.ping_ms = values.get(row.core_profile_id)
            row.status = "online" if row.ping_ms is not None else "unreachable"
            row.last_checked = checked
            row.failures = 0 if row.ping_ms is not None else row.failures + 1
        all_rows.sort(key=self._sort_key)
        self.store.save_servers(all_rows)
        return all_rows

    def connect(self, record: ServerRecord, *, tun: bool, system_proxy: str) -> dict[str, Any]:
        if not record.core_profile_id:
            raise RuntimeError("This server must be refreshed before it can be connected")
        result = self.runtime.connect(record.core_profile_id, tun=tun, system_proxy=system_proxy)
        rows = self.store.load_servers()
        for row in rows:
            if row.id == record.id:
                row.last_connected = utc_now()
        self.store.save_servers(rows)
        settings = self.store.load_settings()
        settings["selected_server_id"] = record.id
        self.store.save_settings(settings)
        return result

    def disconnect(self) -> dict[str, Any]:
        return self.runtime.disconnect()
