'use strict';
const dictionary = {
 newSince:'New in 4.4.0, since version 4', releaseTitle:'More routes. Easier choices.', releaseIntro:'Real subscription refresh, visible diagnostic progress, and accessible reports, while respecting subscriptions you delete.', releaseOne:'Deleted subscriptions stay deleted', releaseTwo:'Subscription refresh and connection deduplication', releaseThree:'Completed/total diagnostic progress and updated Xray', chooseFile:'Choose your device. Use the Windows installer or ARM64 for most modern phones.', navDownload:'Download', stable:'Stable release', title:'Simple connections.<br>Complete control.', intro:'Organize your connections, measure each route, and connect with confidence. One calm workspace for desktop and Android.', getApp:'Get DicodePing', changes:'Release notes ↗', ready:'Ready to connect', profiles:'Profiles', ping:'Latency', speed:'Speed', location:'Location', security:'Security', route1:'Preferred route', route2:'Backup route', illustration:'Interface illustration · sample values', f1:'Each test, independent', f1desc:'Check latency, speed, location, and reachability separately, with live results and cancellation.', f2:'One connected workspace', f2desc:'A fresh profile list and settings in tabs, with matching light and dark themes.', f3:'Cores included', f3desc:'Xray, sing-box, and Mihomo ship with the desktop packages, alongside verification checksums.', downloadEyebrow:'For your device', downloadTitle:'Download DicodePing', allFiles:'All files and SHA-256 ↗', desktop:'Desktop', android:'Android', windowsDesc:'The complete installer, including connection cores.', installer:'Download installer', portable:'Portable ZIP', linuxDesc:'A self-contained package for Linux desktop distributions.', linuxDownload:'Download for Linux', tunPermissions:'TUN mode requires administrator privileges.', macDesc:'Choose the package that matches your Mac processor.', recommended:'For most modern phones', androidDesc:'A signed APK for phones with a 64-bit ARM processor.', apkDownload:'Download APK · arm64-v8a', otherArchitectures:'Other architectures', otherArchitecturesDesc:'For older phones, Intel devices, and emulators.', downloadNote:'Install the APK matching your device architecture. The security test checks configuration settings; the access test measures network reachability.', communityTitle:'Help shape DicodePing', communityDesc:'Follow release updates or report problems with details on GitHub.', telegram:'Telegram channel ↗', report:'Report an issue ↗', footer:'Open source · Built by mcoders', privacy:'Privacy'
};
const elements=[...document.querySelectorAll('[data-i18n]')];
const persian=new Map(elements.map(el=>[el,el.innerHTML]));
const readPreference=(key)=>{try{return localStorage.getItem(key)}catch{return null}};
const savePreference=(key,value)=>{try{localStorage.setItem(key,value)}catch{/* Preferences remain active for this visit. */}};
let language=readPreference('dicode-language')||'fa';
function setLanguage(value){language=value==='en'?'en':'fa';document.documentElement.lang=language;document.documentElement.dir=language==='fa'?'rtl':'ltr';for(const el of elements)el.innerHTML=language==='fa'?persian.get(el):dictionary[el.dataset.i18n]||persian.get(el);document.querySelector('#language').textContent=language==='fa'?'EN':'فارسی';document.querySelector('#theme').setAttribute('aria-label',language==='fa'?'تغییر تم':'Switch theme');document.title=language==='fa'?'DicodePing — اتصال، با کنترل شما':'DicodePing — Connections, under your control';savePreference('dicode-language',language)}
setLanguage(language);document.querySelector('#language').addEventListener('click',()=>setLanguage(language==='fa'?'en':'fa'));
function setTheme(value){document.documentElement.dataset.theme=value;document.querySelector('#theme').setAttribute('aria-pressed',String(value==='dark'));savePreference('dicode-theme',value)}
setTheme(readPreference('dicode-theme')||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'));
document.querySelector('#theme').addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));
const tabs=[...document.querySelectorAll('[role=tab]')];
function selectTab(tab){for(const item of tabs){const selected=item===tab;item.setAttribute('aria-selected',String(selected));item.tabIndex=selected?0:-1;document.getElementById(item.getAttribute('aria-controls')).hidden=!selected}}
for(const tab of tabs){tab.addEventListener('click',()=>selectTab(tab));tab.addEventListener('keydown',event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const index=event.key==='Home'?0:event.key==='End'?tabs.length-1:(tabs.indexOf(tab)+1)%tabs.length;selectTab(tabs[index]);tabs[index].focus()}})}
selectTab(/Android/i.test(navigator.userAgent)?tabs[1]:tabs[0]);
// Pinned links work without the API. Metadata enhances them without replacing
// working download URLs with a stale or incomplete release.
(async()=>{try{const response=await fetch('https://api.github.com/repos/mcodersir/dicodePing/releases/latest',{signal:AbortSignal.timeout(6000)});if(!response.ok)return;const release=await response.json();if(release.draft||release.prerelease||!/^v?\d+\.\d+\.\d+$/.test(release.tag_name))return;const version=release.tag_name.replace(/^v/,'');const [major,minor]=version.split('.').map(Number);if(major<4||(major===4&&minor<2))return;const assets=release.assets||[];for(const link of document.querySelectorAll('.asset')){const asset=assets.find(item=>item.name===`DicodePing-${version}-${link.dataset.asset}`);if(asset?.browser_download_url?.startsWith('https://github.com/mcodersir/dicodePing/releases/download/')){link.href=asset.browser_download_url;link.title=`${(asset.size/1048576).toFixed(1)} MB`}}for(const el of document.querySelectorAll('.version'))el.textContent=version;for(const link of document.querySelectorAll('.release-link'))link.href=release.html_url}catch{/* Static verified release links remain available. */}})();
